# Generated by Django 4.1.4 on 2022-12-23 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('d_auth', '0002_ccodes_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='CCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='d_auth.ccodes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='d_auth.countries'),
        ),
    ]
