# Generated by Django 4.1.4 on 2022-12-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_auth', '0004_user_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
