# Generated by Django 4.1.4 on 2022-12-23 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0003_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replayes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Replay', models.TextField()),
                ('Date', models.DateField(blank=True, null=True)),
                ('Attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('Sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.tickets')),
            ],
        ),
    ]
