# Generated by Django 4.1.4 on 2022-12-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_replayes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=5)),
            ],
        ),
    ]
