# Generated by Django 4.1.4 on 2022-12-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_ccode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='Admin_Status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tickets',
            name='Customer_Status',
            field=models.IntegerField(default=1),
        ),
    ]
