# Generated by Django 4.1.4 on 2022-12-28 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_tickets_admin_status_tickets_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='AddedBy',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='domain',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domain',
            name='Ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='Status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='replayes',
            name='Ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replayes',
            name='Status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tickets',
            name='Ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='Status',
            field=models.IntegerField(default=1),
        ),
    ]
