# Generated by Django 4.1.4 on 2022-12-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_tickets_last_replayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='Last_replayed_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='Last_replayed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
