# Generated by Django 4.1.4 on 2022-12-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_tickets_last_replayed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='Title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
