# Generated by Django 4.1.4 on 2022-12-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='Name',
            field=models.CharField(blank=True, default='attachment', max_length=100, null=True),
        ),
    ]
