# Generated by Django 4.1.4 on 2023-01-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_alter_attachment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='Staff',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
